# Site settings
title: Staaldraad.io
email: etienne@sensepost.com
description: > # this means to ignore newlines until "baseurl:"
	Personal blog about infosec, networks and anything that interests me.
	Includes research and a few interesting things from my day job.
baseurl: "" 
url: "https://staaldraad.github.io" # the base hostname & protocol for your site
twitter_username: kamp_staaldraad 
github_username:  staaldraad

# Build settings
markdown: kramdown
