# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: pygments
markdown: kramdown

permalink: pretty
relative_permalinks: true

title: Staaldraad.io 
tagline: 'Infosec, botnets, broken things'
description: 'About infosec, botnets, networks and things'
url: 'https://staaaldraad.github.io'
baseurl: /

author:
  name: 'Etienne Stalmans'
  email: etienne@sensepost.com
  twitter: _staaldraad 
  bio: Security analyst and researcher

github: 
    repo: https://github.com/staaldraad

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

